# Generated by Django 6.0.6 on 2026-07-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_conversation_patient'),
        ('registration', '0003_alter_insurancepolicy_coverage_end_and_more'),
        ('scheduling', '0006_rename_scheduling__doctor__3dd0a1_idx_appointment_doctor__1ea1ff_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_needed', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Gynecology', 'Gynecology'), ('Neurology', 'Neurology'), ('Psychiatry', 'Psychiatry'), ('Ophthalmology', 'Ophthalmology'), ('ENT', 'ENT'), ('Gastroenterology', 'Gastroenterology'), ('Endocrinology', 'Endocrinology'), ('Pulmonology', 'Pulmonology'), ('Urology', 'Urology'), ('Oncology', 'Oncology'), ('Nephrology', 'Nephrology'), ('Rheumatology', 'Rheumatology'), ('Infectious Disease', 'Infectious Disease'), ('Allergy & Immunology', 'Allergy & Immunology'), ('Emergency Medicine', 'Emergency Medicine')], max_length=80)),
                ('reason', models.TextField()),
                ('urgency', models.CharField(choices=[('emergency', 'emergency'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('routine', 'routine')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'created'), ('accepted', 'accepted'), ('appointment_scheduled', 'appointment_scheduled'), ('patient_confirmed', 'patient_confirmed'), ('visit_completed', 'visit_completed'), ('report_received', 'report_received'), ('closed', 'closed'), ('stalled', 'stalled')], default='created', max_length=30)),
                ('status_history', models.JSONField(blank=True, default=list, help_text='[{"status": "created", "at": "2026-07-10T09:00:00+00:00"}, ...] — appended by services.advance_status(), never edited directly.')),
                ('external_appointment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='core.patient')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to='core.doctor')),
            ],
            options={
                'db_table': 'referrals_referral',
            },
        ),
        migrations.CreateModel(
            name='ConsultationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('followup_recommendations', models.JSONField(blank=True, default=list)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.uploadeddocument')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='referrals.referral')),
            ],
            options={
                'db_table': 'referrals_consultation_report',
            },
        ),
        migrations.CreateModel(
            name='ReferralPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_chart_data', models.JSONField(blank=True, default=dict, help_text='Only the specialty-relevant chart items the AI selected (FR-F2).')),
                ('summary_text', models.TextField(blank=True, help_text='AI-written referral summary.')),
                ('attached_documents', models.JSONField(blank=True, default=list, help_text='List of registration.UploadedDocument ids attached to the package (FR-F4).')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='referrals.referral')),
            ],
            options={
                'db_table': 'referrals_package',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('practice_name', models.CharField(blank=True, max_length=150)),
                ('specialty', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Gynecology', 'Gynecology'), ('Neurology', 'Neurology'), ('Psychiatry', 'Psychiatry'), ('Ophthalmology', 'Ophthalmology'), ('ENT', 'ENT'), ('Gastroenterology', 'Gastroenterology'), ('Endocrinology', 'Endocrinology'), ('Pulmonology', 'Pulmonology'), ('Urology', 'Urology'), ('Oncology', 'Oncology'), ('Nephrology', 'Nephrology'), ('Rheumatology', 'Rheumatology'), ('Infectious Disease', 'Infectious Disease'), ('Allergy & Immunology', 'Allergy & Immunology'), ('Emergency Medicine', 'Emergency Medicine')], db_index=True, max_length=80)),
                ('address', models.JSONField(blank=True, default=dict, help_text='{"line1": ..., "city": ..., "postal_code": ..., "lat": ..., "lng": ...} — postal_code (or lat/lng) is what distance ranking uses.')),
                ('accepted_insurances', models.JSONField(blank=True, default=list, help_text='["BlueShield", "Star Health", ...]')),
                ('languages', models.JSONField(blank=True, default=list, help_text='["en", "hi", "mr"]')),
                ('accepting_new_patients', models.BooleanField(default=True)),
                ('contact_channel', models.CharField(choices=[('phone', 'phone'), ('e_referral', 'e_referral'), ('email', 'email'), ('api', 'api')], max_length=20)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('internal_doctor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_profile', to='core.doctor')),
            ],
            options={
                'db_table': 'referrals_specialist',
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='specialist',
            field=models.ForeignKey(blank=True, help_text='Nullable until match_specialists() picks one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='referrals.specialist'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status'], name='referrals_r_status_50a3e5_idx'),
        ),
    ]
