# Generated by Django 6.0.6 on 2026-07-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistOutreachTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('phone', 'phone'), ('e_referral', 'e_referral'), ('email', 'email'), ('api', 'api')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('failed', 'failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_tasks', to='referrals.referral')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.specialist')),
            ],
            options={
                'db_table': 'referrals_outreach_task',
            },
        ),
    ]
