# Generated by Django 6.0.6 on 2026-07-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_conversation_patient'),
        ('referrals', '0002_specialistoutreachtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referring_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to='core.doctor'),
        ),
    ]
