# Generated by Django 6.0.6 on 2026-07-08 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_auditevent_table_alter_conversation_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100)),
                ('provider_name', models.CharField(max_length=100)),
                ('coverage_details', models.TextField()),
                ('coverage_start', models.DateField()),
                ('coverage_end', models.DateField()),
                ('eligibility_status', models.CharField(choices=[('unknown', 'unknown'), ('eligible', 'eligible'), ('ineligible', 'ineligible')], max_length=50)),
                ('eligibility_checked_at', models.DateTimeField(blank=True, null=True)),
                ('raw_extraction', models.JSONField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'db_table': 'patient_insurancepolicy',
            },
        ),
        migrations.CreateModel(
            name='IntakeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_profile', models.JSONField(blank=True, default=dict, help_text='Structured clinical profile extracted from the intake form.')),
                ('summary_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'db_table': 'patient_intakesummary',
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('insurance_card', 'insurance_card'), ('id_card', 'id_card'), ('prescription', 'prescription'), ('lab_report', 'lab_report'), ('referral_letter', 'referral_letter'), ('other', 'other')], max_length=100)),
                ('file', models.FileField(upload_to='uploaded_documents/')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'db_table': 'patient_documents',
            },
        ),
    ]
