# Generated by Django 6.0.6 on 2026-07-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='member_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='Structured fields read from the document by the AI, e.g. policy number, provider name, test results.', null=True),
        ),
    ]
