# Generated by Django 6.0.6 on 2026-07-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_insurancepolicy_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='coverage_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='coverage_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
