# Generated by Django 6.0.6 on 2026-07-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_insurancepolicy_coverage_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='document_type',
            field=models.CharField(choices=[('insurance_card', 'insurance_card'), ('id_card', 'id_card'), ('prescription', 'prescription'), ('lab_report', 'lab_report'), ('referral_letter', 'referral_letter'), ('consultation_report', 'consultation_report'), ('other', 'other')], max_length=100),
        ),
    ]
