# Generated by Django 6.0.6 on 2026-07-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_uploadeddocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='plan',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='document_type',
            field=models.CharField(choices=[('insurance_card', 'insurance_card'), ('id_card', 'id_card'), ('prescription', 'prescription'), ('lab_report', 'lab_report'), ('referral_letter', 'referral_letter'), ('consultation_report', 'consultation_report'), ('imaging_report', 'imaging_report'), ('other', 'other')], max_length=100),
        ),
    ]
