# Generated by Django 6.0.6 on 2026-07-11 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_conversation_patient'),
        ('referrals', '0003_alter_referral_referring_doctor'),
        ('registration', '0004_alter_uploadeddocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=120)),
                ('plan', models.CharField(blank=True, max_length=120, null=True)),
                ('cpt_pattern', models.CharField(blank=True, help_text='glob/regex against TreatmentOrder.cpt_code', max_length=60, null=True)),
                ('icd10_pattern', models.CharField(blank=True, help_text='glob/regex against TreatmentOrder.icd10_code', max_length=60, null=True)),
                ('medication_pattern', models.CharField(blank=True, help_text='glob/regex against TreatmentOrder.medication', max_length=60, null=True)),
                ('network_requirement', models.CharField(blank=True, choices=[('in_network', 'in_network'), ('any', 'any')], max_length=20, null=True)),
                ('requires_auth', models.BooleanField()),
                ('submission_channel', models.CharField(choices=[('api', 'api'), ('epa', 'epa'), ('portal', 'portal'), ('fax', 'fax')], max_length=20)),
                ('required_documentation', models.JSONField(blank=True, default=list, help_text='List of evidence categories (FR-P2), e.g. ["diagnosis", "physician_notes", "imaging_reports"].')),
            ],
            options={
                'db_table': 'priorauth_payer_rule',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('detected', 'detected'), ('gathering_evidence', 'gathering_evidence'), ('ready_for_review', 'ready_for_review'), ('submitted', 'submitted'), ('under_review', 'under_review'), ('info_requested', 'info_requested'), ('approved', 'approved'), ('denied', 'denied')], default='detected', max_length=30)),
                ('status_history', models.JSONField(blank=True, default=list, help_text='[{"status": "detected", "at": "..."}, ...] — appended by services.advance_status(), never edited directly.')),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('appeal_suggested', models.BooleanField(default=False, help_text='FR-P7')),
                ('external_reference', models.CharField(blank=True, help_text="The payer's own case number, once submitted.", max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorization_requests', to='registration.insurancepolicy')),
                ('matched_rule', models.ForeignKey(blank=True, help_text='Nullable — rules can be edited/retired without deleting past requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_requests', to='priorauth.payerrule')),
            ],
            options={
                'db_table': 'priorauth_authorization_request',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographics_snapshot', models.JSONField(blank=True, default=dict)),
                ('codes', models.JSONField(blank=True, default=dict, help_text='CPT/ICD-10 codes on the order.')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Gathered items by category (FR-P2).')),
                ('reviewer_summary', models.TextField(blank=True, help_text='AI medical-necessity summary (FR-P3).')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='priorauth.authorizationrequest')),
            ],
            options={
                'db_table': 'priorauth_authorization_package',
            },
        ),
        migrations.CreateModel(
            name='PayerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'outbound'), ('inbound', 'inbound')], max_length=10)),
                ('content', models.TextField(help_text='Full audit trail of everything exchanged (FR-P6).')),
                ('parsed', models.JSONField(blank=True, default=dict, help_text='AI structured interpretation (Phase 4).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='priorauth.authorizationrequest')),
            ],
            options={
                'db_table': 'priorauth_payer_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('medication', 'medication'), ('imaging', 'imaging'), ('procedure', 'procedure'), ('device', 'device'), ('therapy', 'therapy')], max_length=20)),
                ('cpt_code', models.CharField(blank=True, max_length=10, null=True)),
                ('icd10_code', models.CharField(blank=True, max_length=10, null=True)),
                ('medication', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordering_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_orders_placed', to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_orders', to='core.patient')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_orders', to='referrals.referral')),
            ],
            options={
                'db_table': 'priorauth_treatment_order',
            },
        ),
        migrations.AddField(
            model_name='authorizationrequest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorization', to='priorauth.treatmentorder'),
        ),
        migrations.AddIndex(
            model_name='authorizationrequest',
            index=models.Index(fields=['status'], name='priorauth_a_status_b2f1ce_idx'),
        ),
    ]
