# Generated by Django 6.0.6 on 2026-07-12 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_conversation_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('clinical_goal', models.TextField()),
                ('cohort_criteria', models.JSONField(blank=True, default=dict, help_text='Shared criteria schema (FR-O1; reused by caregaps). Defined and validated by outreach.services.build_cohort().')),
                ('channel_plan', models.JSONField(blank=True, default=list, help_text='Ordered escalation plan, e.g. [{"channel": "sms", "wait_days": 0}, {"channel": "email", "wait_days": 3}, {"channel": "voice", "wait_days": 7}]')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('running', 'running'), ('paused', 'paused'), ('completed', 'completed')], default='draft', max_length=20)),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='When/how often waves should dispatch.')),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'outreach_campaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('identified', 'identified'), ('contacted', 'contacted'), ('responded', 'responded'), ('scheduled', 'scheduled'), ('completed', 'completed'), ('snoozed', 'snoozed'), ('opted_out', 'opted_out'), ('unreachable', 'unreachable')], default='identified', max_length=20)),
                ('snooze_until', models.DateField(blank=True, help_text='Edge Case 14.', null=True)),
                ('channel_attempts', models.JSONField(blank=True, default=list, help_text='[{"channel": "sms", "at": "2026-07-10T09:00:00+00:00", "message_id": 12}, ...]')),
                ('outreach_reason', models.CharField(help_text='FR-O3.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_memberships', to='core.doctor')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='outreach.campaign')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_memberships', to='core.patient')),
            ],
            options={
                'db_table': 'outreach_campaign_member',
            },
        ),
        migrations.CreateModel(
            name='InboundResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('classified_intent', models.CharField(blank=True, choices=[('book', 'book'), ('snooze', 'snooze'), ('opt_out', 'opt_out'), ('question', 'question'), ('unclear', 'unclear')], max_length=20)),
                ('snooze_until', models.DateField(blank=True, null=True)),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_responses', to='outreach.campaignmember')),
            ],
            options={
                'db_table': 'outreach_inbound_response',
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.IntegerField(help_text='Which escalation step this message belongs to.')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='outreach.campaignmember')),
                ('notification', models.ForeignKey(help_text='Delivery itself is handled by core.notifications.notify().', on_delete=django.db.models.deletion.CASCADE, related_name='outreach_message', to='core.sentnotification')),
            ],
            options={
                'db_table': 'outreach_outbound_message',
            },
        ),
        migrations.AddIndex(
            model_name='campaignmember',
            index=models.Index(fields=['campaign', 'state'], name='outreach_ca_campaig_4add23_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignmember',
            constraint=models.UniqueConstraint(fields=('campaign', 'patient'), name='unique_campaign_patient'),
        ),
    ]
