# Generated by Django 6.0.6 on 2026-07-13 20:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_conversation_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list, help_text='e.g. ["hours", "locations"]')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'frontdesk_knowledge_article',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='frontdesk_k_search__5db52f_gin')],
            },
        ),
        migrations.CreateModel(
            name='PatientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('web', 'Web'), ('portal', 'Portal'), ('app', 'App'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('voice', 'Voice')], default='web', max_length=20)),
                ('authenticated', models.BooleanField(default=False)),
                ('pending_intents', models.JSONField(blank=True, default=list, help_text='Intents queued behind the auth gate, resumed after step-up (FR-A3).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frontdesk_session', to='core.conversation')),
                ('patient', models.ForeignKey(blank=True, help_text='Null until authenticated (FR-A3).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontdesk_sessions', to='core.patient')),
            ],
            options={
                'db_table': 'frontdesk_patient_session',
            },
        ),
        migrations.CreateModel(
            name='IntentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('appointment', 'appointment'), ('refill', 'refill'), ('referral_status', 'referral_status'), ('pa_status', 'pa_status'), ('care_gap', 'care_gap'), ('symptoms', 'symptoms'), ('faq', 'faq'), ('other', 'other')], max_length=20)),
                ('target_agent', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('routed', 'routed'), ('completed', 'completed'), ('escalated', 'escalated')], default='routed', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text="The router's extraction.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='frontdesk.patientsession')),
            ],
            options={
                'db_table': 'frontdesk_intent_route',
                'indexes': [models.Index(fields=['session', 'status'], name='frontdesk_i_session_cea5a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mental_health', 'mental_health'), ('stroke', 'stroke'), ('insurance_dispute', 'insurance_dispute'), ('controlled_substance', 'controlled_substance'), ('unanswered_question', 'unanswered_question'), ('manual_review', 'manual_review')], max_length=30)),
                ('priority', models.CharField(choices=[('critical', 'critical'), ('high', 'high'), ('normal', 'normal')], default='normal', max_length=10)),
                ('summary', models.TextField()),
                ('status', models.CharField(choices=[('open', 'open'), ('claimed', 'claimed'), ('resolved', 'resolved')], default='open', max_length=10)),
                ('claimed_by', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontdesk_tasks', to='core.patient')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='frontdesk.patientsession')),
            ],
            options={
                'db_table': 'frontdesk_staff_task',
                'indexes': [models.Index(fields=['status', 'priority'], name='frontdesk_s_status_74feb2_idx')],
            },
        ),
    ]
