# Generated by Django 6.0.6 on 2026-07-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsession',
            name='channel_identifier',
            field=models.CharField(blank=True, db_index=True, help_text='Raw sender address (phone number) for channel-originated sessions with no signed token to correlate by -- SMS/WhatsApp replies land here via the Phase 6 channel adapter. Blank for web/app sessions opened through /frontdesk/start.', max_length=32),
        ),
    ]
