# Generated by Django 6.0.6 on 2026-07-13 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_conversation_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('population_criteria', models.JSONField(blank=True, default=dict, help_text='Same schema as Campaign.cohort_criteria — who the rule applies to.')),
                ('care_item_type', models.CharField(choices=[('screening', 'screening'), ('test', 'test'), ('vaccination', 'vaccination'), ('visit', 'visit'), ('followup', 'followup')], max_length=20)),
                ('care_item_code', models.CharField(help_text='Matched against ClinicalEvent.code (LOINC/CPT/CVX-style).', max_length=40)),
                ('frequency_days', models.IntegerField(help_text='Max allowed gap in days since the last matching ClinicalEvent.')),
                ('risk_tier', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], help_text='FR-G3.', max_length=10)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'caregaps_clinical_guideline',
            },
        ),
        migrations.CreateModel(
            name='CareGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'open'), ('outreach', 'outreach'), ('scheduled', 'scheduled'), ('completed', 'completed'), ('closed', 'closed')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('due_since', models.DateField(help_text='When the care item became overdue.')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_gaps', to='core.patient')),
            ],
            options={
                'db_table': 'caregaps_care_gap',
            },
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_text', models.TextField(blank=True, help_text='AI patient-facing plan (Phase 4).')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('sent', 'sent'), ('accepted', 'accepted'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('recycled', 'recycled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gaps', models.ManyToManyField(blank=True, related_name='care_plans', to='caregaps.caregap')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_plans', to='core.patient')),
            ],
            options={
                'db_table': 'caregaps_care_plan',
            },
        ),
        migrations.CreateModel(
            name='ClinicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lab', 'lab'), ('vaccination', 'vaccination'), ('visit', 'visit'), ('procedure', 'procedure'), ('diagnosis', 'diagnosis')], max_length=20)),
                ('code', models.CharField(db_index=True, help_text='LOINC/CPT/CVX-style.', max_length=40)),
                ('value', models.JSONField(blank=True, default=dict, help_text='e.g. {"hba1c": 8.4}')),
                ('occurred_at', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_events', to='core.patient')),
            ],
            options={
                'db_table': 'caregaps_clinical_event',
            },
        ),
        migrations.AddField(
            model_name='caregap',
            name='closing_event',
            field=models.ForeignKey(blank=True, help_text='FR-G8 evidence the gap was really met.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_gaps', to='caregaps.clinicalevent'),
        ),
        migrations.AddField(
            model_name='caregap',
            name='guideline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gaps', to='caregaps.clinicalguideline'),
        ),
        migrations.AddIndex(
            model_name='clinicalevent',
            index=models.Index(fields=['patient', 'code', '-occurred_at'], name='caregaps_cl_patient_56b28a_idx'),
        ),
        migrations.AddIndex(
            model_name='caregap',
            index=models.Index(fields=['status', 'due_since'], name='caregaps_ca_status_b055a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='caregap',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'closed'), _negated=True), fields=('patient', 'guideline'), name='unique_live_gap_per_patient_guideline'),
        ),
    ]
