# Generated by Django 6.0.6 on 2026-07-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_conversation_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('erx_identifier', models.CharField(blank=True, help_text='e-prescription network ID.', max_length=60, null=True)),
            ],
            options={
                'db_table': 'pharmacy',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=150)),
                ('dose', models.CharField(max_length=60)),
                ('quantity', models.CharField(max_length=40)),
                ('refills_allowed', models.IntegerField(help_text='Total refills the prescriber authorized (FR-M4).')),
                ('refills_used', models.IntegerField(default=0)),
                ('prescribed_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('expired', 'Expired')], default='active', max_length=20)),
                ('required_labs', models.JSONField(blank=True, default=list, help_text='List of {"test": ..., "max_age_days": ...} that must be current before a refill (FR-M3).')),
                ('followup_required', models.BooleanField(default=False)),
                ('is_controlled_substance', models.BooleanField(default=False, help_text='Controlled substances are NEVER auto-processed — always a human decision (PRD Edge Case 12).')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='RefillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('eligibility_check', 'Eligibility Check'), ('paused', 'Paused'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('visit_required', 'Visit Required'), ('sent_to_pharmacy', 'Sent to Pharmacy'), ('ready_for_pickup', 'Ready for Pickup')], default='received', max_length=20)),
                ('pause_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('renewal_summary', models.JSONField(blank=True, default=dict, help_text='Structured physician-facing data (FR-M5).')),
                ('summary_text', models.TextField(blank=True, help_text='AI one-paragraph physician summary.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refills.pharmacy')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refills.prescription')),
            ],
            options={
                'db_table': 'refill_request',
            },
        ),
    ]
