# Generated by Django 6.0.6 on 2026-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='active', max_length=20),
        ),
    ]
