# Generated by Django 6.0.6 on 2026-07-06 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('scheduling', '0003_remove_message_conversation_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reason_for_visit',
        ),
        migrations.RemoveField(
            model_name='waitlist',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.CharField(blank=True, help_text='Assigned room, if needed (FR-S4).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('scheduling', 'scheduling'), ('triage', 'triage'), ('outreach', 'outreach'), ('caregaps', 'caregaps'), ('referrals', 'referrals'), ('priorauth', 'priorauth')], default='scheduling', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='urgency',
            field=models.CharField(choices=[('emergency', 'emergency'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('routine', 'routine')], default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='preferred_window',
            field=models.JSONField(blank=True, default=dict, help_text='Date range / times of day the patient wants, e.g. {"from": "2026-07-10", "to": "2026-07-14", "times": ["morning"]}'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='specialty',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='urgency',
            field=models.CharField(choices=[('emergency', 'emergency'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('routine', 'routine')], default='routine', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('no_show', 'no_show')], default='booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('offered', 'offered'), ('booked', 'booked'), ('expired', 'expired')], default='waiting', max_length=20),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'start_time'], name='scheduling__doctor__3dd0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['doctor', 'status', 'urgency', 'created_at'], name='scheduling__doctor__81b11f_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'start_time'), name='unique_doctor_start'),
        ),
    ]
