# Generated by Django 6.0.6 on 2026-07-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='urgency',
            field=models.CharField(choices=[('emergency', 'emergency'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('routine', 'routine')], max_length=20),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='specialty',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='urgency',
            field=models.CharField(choices=[('emergency', 'emergency'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('routine', 'routine')], max_length=20),
        ),
    ]
