# Generated by Django 6.0.6 on 2026-07-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_appointment_reason_alter_appointment_urgency_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_doctor__1ea1ff_idx',
            old_name='scheduling__doctor__3dd0a1_idx',
        ),
        migrations.RenameIndex(
            model_name='waitlist',
            new_name='waitlist_doctor__61a541_idx',
            old_name='scheduling__doctor__81b11f_idx',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
        migrations.AlterModelTable(
            name='waitlist',
            table='waitlist',
        ),
    ]
