# Generated by Django 6.0.6 on 2026-07-06 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('portal', 'Portal'), ('app', 'App'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('voice', 'Voice')], default='sms', max_length=20)),
                ('agent_context', models.JSONField(blank=True, default=dict, help_text='Scratch state passed between agents, e.g. {"intent_stack": ["book_appointment"], "verified": false, "active_agent": "scheduling"}')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Gynecology', 'Gynecology'), ('Neurology', 'Neurology'), ('Psychiatry', 'Psychiatry'), ('Ophthalmology', 'Ophthalmology'), ('ENT', 'ENT'), ('Gastroenterology', 'Gastroenterology'), ('Endocrinology', 'Endocrinology'), ('Pulmonology', 'Pulmonology'), ('Urology', 'Urology'), ('Oncology', 'Oncology'), ('Nephrology', 'Nephrology'), ('Rheumatology', 'Rheumatology'), ('Infectious Disease', 'Infectious Disease'), ('Allergy & Immunology', 'Allergy & Immunology'), ('Emergency Medicine', 'Emergency Medicine')], max_length=50)),
                ('working_hours', models.JSONField(blank=True, default=dict, help_text='{"mon": [["09:00", "13:00"], ["14:00", "17:00"]], "tue": [["09:00", "17:00"]], ...}')),
                ('avg_consult_minutes', models.IntegerField(default=20)),
                ('buffer_minutes', models.IntegerField(default=10)),
                ('holidays', models.JSONField(blank=True, default=list, help_text='["2026-01-01", "2026-08-15", "2026-12-25"]')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Event name, e.g. 'registration.completed', 'appointment.booked'.", max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Event data passed to subscribers.')),
                ('processed', models.BooleanField(default=False, help_text='Whether all subscribers have handled this event.')),
                ('error', models.TextField(blank=True, help_text='Subscriber failure detail, if processing failed. Null on success.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.JSONField(blank=True, default=dict, help_text='\n        {\n            "line1": "",\n            "line2": "",\n            "city": "",\n            "state": "",\n            "zip": ""\n        }\n        ')),
                ('emergency_contact', models.JSONField(blank=True, default=dict, help_text='\n        {\n            "Contact 1": "",\n            "Contact 2": "",\n            "Contact 3": "",\n        }\n        ')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('gu', 'Gujarati'), ('bn', 'Bengali'), ('ml', 'Malayalam'), ('pa', 'Punjabi')], default='en', max_length=10)),
                ('preferred_pharmacy', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_status', models.CharField(choices=[('in_process', 'in_process'), ('verified', 'verified'), ('duplicate_detected', 'duplicate_detected'), ('complete', 'complete')], max_length=20)),
                ('communication_preferences', models.JSONField(blank=True, default=dict, help_text='\n                    {\n                    "sms": false,\n                    "email": true,\n                    "voice": true,\n                    "whatsapp": false\n                    }\n                    ')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Patient', 'Patient'), ('Assistant', 'Assistant'), ('System', 'System'), ('Staff', 'Staff')], max_length=10)),
                ('content', models.TextField()),
                ('agent_context', models.JSONField(blank=True, default=dict, help_text='Scratch state passed between agents, e.g. {"intent_stack": ["book_appointment"], "verified": false, "active_agent": "scheduling"}')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('email', 'email'), ('whatsapp', 'whatsapp')], max_length=10)),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the code. Never store the plain code.', max_length=128)),
                ('expires_at', models.DateTimeField(help_text='Expires 10 minutes after the code is generated.')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts made.')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, help_text='Maximum allowed verification attempts.')),
                ('consumed_at', models.DateTimeField(blank=True, help_text='Timestamp when the code was successfully used. Null if unused.', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('patient', 'patient'), ('staff', 'staff'), ('agent', 'agent'), ('system', 'system')], max_length=10)),
                ('actor_id', models.CharField(help_text='Identifier of the actor that performed the action, e.g. patient id, staff user id, or agent name.', max_length=100)),
                ('action', models.CharField(help_text="What happened, e.g. 'appointment.booked', 'patient.verified', 'otp.failed'.", max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Extra detail about the event, e.g. old/new values, reason, target object ids.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the event occurred. Set once at creation and never changes.')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SentNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('email', 'email'), ('whatsapp', 'whatsapp')], max_length=10)),
                ('recipient', models.CharField(help_text='Destination the notification was sent to, e.g. a phone number or email address.', max_length=255)),
                ('rendered_content', models.TextField(help_text='Final message body actually sent to the recipient, after template rendering.')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('delivered', 'delivered'), ('failed', 'failed')], max_length=10)),
                ('provider_message_id', models.CharField(blank=True, help_text='Message ID returned by the external notification provider.', max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
