# Generated by Django 6.0.6 on 2026-07-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditevent',
            table='patient_auditevent',
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='patient_conversation',
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
        migrations.AlterModelTable(
            name='eventlog',
            table='event_log',
        ),
        migrations.AlterModelTable(
            name='message',
            table='patient_message',
        ),
        migrations.AlterModelTable(
            name='otpchallenge',
            table='patient_otpchallenge',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
        migrations.AlterModelTable(
            name='sentnotification',
            table='patient_sentnotification',
        ),
    ]
