# Generated by Django 6.0.6 on 2026-07-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditevent_table_alter_conversation_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identity_verified',
            field=models.BooleanField(default=False),
        ),
    ]
