# Generated by Django 6.0.6 on 2026-07-09 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_conversation_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symptom_keywords', models.JSONField(blank=True, default=list, help_text='List of keywords associated with the clinical protocol for symptom matching.')),
                ('question_flow', models.JSONField(blank=True, default=list, help_text='Structured representation of the question flow for the clinical protocol.')),
                ('disposition_rules', models.JSONField(blank=True, default=dict, help_text='Rules for determining patient disposition based on reported symptoms and findings.')),
                ('version', models.CharField(default='1.0', help_text='Version of the clinical protocol.', max_length=20)),
                ('approved_by', models.CharField(blank=True, help_text='Name of the person or entity that approved the clinical protocol.', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the clinical protocol is currently active and in use.')),
            ],
            options={
                'db_table': 'clinical_protocol',
            },
        ),
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_symptoms', models.JSONField(blank=True, default=dict, help_text='Structured data of reported symptoms.')),
                ('findings', models.JSONField(blank=True, default=dict, help_text='Structured data of findings from the assessment.')),
                ('acuity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency'), ('minimal', 'Minimal')], help_text='The acuity level of the patient based on the assessment.', max_length=50)),
                ('disposition', models.CharField(choices=[('ed_now', 'Go to Emergency Department Now'), ('same_day', 'Same Day'), ('24_48h', '24-48 Hours'), ('routine', 'Routine'), ('self_care', 'Self-Care')], help_text='The recommended disposition for the patient based on the assessment.', max_length=50)),
                ('summary_text', models.TextField(help_text='A concise summary of the assessment, including presenting symptoms and findings.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('clinical_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.clinicalprotocol')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'db_table': 'triage_assessment',
            },
        ),
        migrations.CreateModel(
            name='EscalationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_agent', models.CharField(help_text='The agent (human or AI) that generated the escalation alert.', max_length=100)),
                ('category', models.CharField(choices=[('emergency', 'Emergency'), ('mental_health', 'Mental Health'), ('stroke', 'Stroke'), ('controlled_substance', 'Controlled Substance'), ('other', 'Other'), ('insurance_dispute', 'Insurance Dispute')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='The priority level of the escalation alert.', max_length=20)),
                ('summary', models.TextField(help_text='A brief summary of the reason for the escalation alert.')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='Timestamp when the alert was acknowledged by a human.', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', help_text='The current status of the escalation alert.', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.triageassessment')),
            ],
            options={
                'db_table': 'escalation_alert',
            },
        ),
    ]
