# Generated by Django 6.0.6 on 2026-07-10 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_alter_triageassessment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageassessment',
            name='clinical_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.clinicalprotocol'),
        ),
    ]
