# Generated by Django 6.0.6 on 2026-07-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_alter_triageassessment_clinical_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationalert',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triage.triageassessment'),
        ),
    ]
