# Generated by Django 6.0.6 on 2026-07-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_alter_escalationalert_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='When the assessment completed or escalated.', null=True),
        ),
    ]
